export const ResponseMessage = {
    INTERNAL_SERVER_ERROR: "Internal server error!",
    USER_CREATED: "You've successfully registered.",
    // USER_CREATED: "You've successfully registered. We've sent you a verification email.",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    USER_NOT_CREATED: "User not created!",
    USER_ALREADY_CREATED: "User already created!",
    USER_LOGGED_IN: "User logged in.",
    INVALID_PASSWORD: "Invalid Password!",
    ACCOUNT_IS_INACTIVE: "Account inactive.",
    YOUR_ACCOUNT_NOT_VERIFIED: "Your account not verified!",
    USER_NOT_FOUND: "User not found!",
    ALL_FIELDS_REQUIRED: "All fields are required!",
    ADMIN_LOGGED_IN: "Admin logged in.",
    ADMIN_NOT_FOUND: "Admin not found!",
    USER_ACTIVATED: "User Activated",
    USER_IN_ACTIVATED: "User In-Activated",
    TOKEN_NOT_VALID: "Token not valid!",
    ACCOUNT_DEACTIVATED: "Account deactivated!",
    OLD_PASSWORD_INVALID: "Old password invalid!",
    OLD_AND_NEW_PASSWORD_SAME: "Old and new password can not be same!",
    PASSWORD_CHANGED: "Password changed successfully.",
    RESET_PASSWORD_ERROR: "Failed to reset password!",
    ADMIN_NOT_EXIST: "Admin not found!",
    USER_FETCHED: "User fetched successfully.",
    GENRE_ALREADY_CREATED: "Genre already exist!",
    GENRE_CREATED: "Genre created successfully.",
    GENRE_NOT_CREATED: "Failed to create genre!",
    GENRE_UPDATED: "Genre updated successfully.",
    GENRE_NOT_UPDATED: "Failed to update genre!",
    GENRE_FETCHED: "Genre fetched.",
    GENRE_NOT_FOUND: "Genre not found!",
    GENRE_DELETED: "Genre deleted successfully.",
    GENRE_NOT_DELETED: "Failed to delete genre!",
    GAME_ALREADY_CREATED: "Game already created!",
    GAME_CREATED: "Game created successfully.",
    GAME_NOT_CREATED: "Failed to create game!",
    GAME_NOT_UPDATED: "Failed to update game!",
    GAME_UPDATED: "Game updated successfully.",
    GAME_NOT_FOUND: "Game not found!",
    GAME_FETCHED: "Game fetched successfully.",
    GAME_NOT_DELETED: "Failed to delete game!",
    GAME_DELETED: "Game deleted.",
    RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
    INVALID_OTP: "Invalid otp!",
    RESET_PASSWORD: "Password reset successfully.",
    PASSWORD_NOT_MATCH: "Password not match!",
    OLD_NEW_PASSWORD_ARE_MATCH: "Old and new password are match!",
    VERIFICATION_COMPLETED: "Verification complete.",
    PLATFORM_ALREADY_CREATED: "Platform already created!",
    PLATFORM_UPDATED: "Platform updated successfully.",
    PLATFORM_NOT_UPDATED: "Platform not updated!",
    PLATFORM_CREATED: "Platform created.",
    PLATFORM_NOT_CREATED: "Platform not created!",
    PLATFORM_FETCHED: "Platform fetched.",
    PLATFORM_NOT_FOUND: "Platform not found!",
    PLATFORM_DELETED: "Platform deleted.",
    PLATFORM_NOT_DELETED: "Platform not deleted!"
}